ALTER TABLE "CompanySettings" ADD COLUMN "stampSize" INTEGER NOT NULL DEFAULT 55;
ALTER TABLE "CompanySettings" ADD COLUMN "stampPosX" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CompanySettings" ADD COLUMN "stampPosY" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CompanySettings" ADD COLUMN "stampRotate" INTEGER NOT NULL DEFAULT 0;
